# SELF-HOSTED BUILD PIPELINE 
# POWERSHELL CONFIG

trigger:
- main

pool:
  name: Self-Hosted Pipeline
  demands: 
  - agent.name -equals Agent

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |  
        $url = "http://localhost:5005/removeallappxpackages"
        $pipeline = Invoke-RestMethod -Uri $url -Method Get;
        Write-Host "Pipeline = $($pipeline | ConvertTo-Json -Depth 100)"

# Option two with unimplimented logic
# Leaving config for future development

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $url = "$($env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI)$env:SYSTEM_TEAMPROJECTID/_apis/build/definitions/$($env:SYSTEM_DEFINITIONID)?api-version=5.0"
              Write-Host "URL: $url"
              $pipeline = Invoke-RestMethod -Uri $url -Headers @{
                  Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"
              }
              Write-Host "Pipeline = $($pipeline | ConvertTo-Json -Depth 100)"
  env:
     SYSTEM_ACCESSTOKEN: $(System.AccessToken)



